baseURL = "https://www.wrdeoftheday.co.uk"
languageCode = "en-us"
title = "Wrde Of The Day"
theme = "hugo-theme-nix"
paginate = 5
config = "config.toml"
tags = ["blog", "cv"]
googleAnalytics = ""

[Params]
    tagline = "Wrde of the Day"
    Name = "wrde of the day"
    HeaderUsername = "wrde"
    HeaderHostname = "man"
    About = "Full-stack developer and relapsed physicist"
    ProfilePicture = "images/background.jpg"
    customCSS = ""

    GithubID = "wrdeman"
    LinkedInID = "simon-osborne-b016513"
    # facebook = ""

    copyright = false
    credit = true

[[menu.header]]
  name = "post"
  url = "/post"
  weight = 1

[[menu.header]]
  name = "About"
  url = "/about"
  weight = 1

