baseURL = "https://www.wrdeoftheday.co.uk"
languageCode = "en-us"
title = "Wrde Of The Day"
theme = "hugo-theme-nix"
paginate = 5
config = "config.toml"
tags = ["blog", "cv"]

[Params]
    tagline = "Wrde of the Day"
    Name = "wrde of the day"
    HeaderUsername = "wrde"
    HeaderHostname = "man"
    About = "Full-stack developer, relapsed physicist and sometime trumpeter"
    ProfilePicture = "images/background.jpg"
    customCSS = ""

    GithubID = "wrdeman"
    LinkedInID = "simon-osborne-b016513"
    # facebook = ""
    GoogleAnalytics = "UA-146772833-1"

    copyright = false
    credit = true

[[menu.header]]
  name = "posts"
  url = "/posts"
  weight = 1

[[menu.header]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.header]]
  name = "music"
  url = "/music"
  weight = 1


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true
