version: 2
jobs:
  build:
    docker:
      - image: wrdeman/docker-min-hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:8c:e1:f5:47:cf:54:64:c1:64:7f:45:bc:14:fc:90" 
      # checkout the repository
      - run: apt-get -qq update; apt-get -y install git ca-certificates
      - run: git clone git@github.com:wrdeman/wrdeoftheday.git
      # - run: git clone git@github.com:wrdeman/wrdeoftheday.git
      # install git submodules for managing third-party dependencies
      - run: git config user.email "wrdeplay@gmail.com"
      - run: git config user.name "ci-build"
      - run: 
          name: "Pull themes"
          command: |
            git clone https://github.com/wrdeman/hugo-theme-nix themes/hugo-theme-nix
      - run: sh publish.sh

