version: 2
jobs:
  build:
    docker:
      - image: wrdeman/docker-min-hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - add_ssh_keys:
          fingerprints:
            - "55:de:8d:86:89:ba:6a:58:a5:0f:44:f1:1f:c7:a5:9c"
      # checkout the repository
      - run: apt-get -qq update; apt-get -y install git
      - checkout
      # - run: git clone git@github.com:wrdeman/wrdeoftheday.git
      # install git submodules for managing third-party dependencies
      - run: git config user.email "wrdeplay@gmail.com"
      - run: git config user.name "ci-build"
      - run: git submodule sync && git submodule update --init
      - run: sh publish.sh

