version: 2
jobs:
  build:
    docker:
      - image: wrdeman/docker-min-hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a4:39:19:99:e2:40:e3:0c:fd:d3:87:59:a8:a7:05:d3"
      # checkout the repository
      - run: apt-get -qq update; apt-get -y install git ca-certificates
      - checkout
      - run: git checkout master
      # - run: git clone git@github.com:wrdeman/wrdeoftheday.git
      # install git submodules for managing third-party dependencies
      - run: git config user.email "wrdeplay@gmail.com"
      - run: git config user.name "ci-build"
      - run: 
          name: "Pull themes"
          command: |
            git clone https://github.com/wrdeman/hugo-theme-nix themes/hugo-theme-nix
      - run: hugo -d docs
      - run: git add --all && git commit -m "Publishing to gh-pages (publish.sh)"
      - run: git push

